Repository VirtoCommerce/vc-demo-xapi-app, pull requests merged in 2021-08, with the labels that each got.

#23 VDS-1979: Load and save dynamic properties for organization
  package.json
  src/app/app.module.ts
  src/app/graphql.module.ts
  src/app/graphql/mutations/update-memberDynamicProperties.graphql
  src/app/graphql/queries/get-dictionaryDynamicProperty.graphql
  src/app/graphql/types/getDictionaryDynamicPropery.ts
  src/app/graphql/types/globalTypes.ts
  src/app/graphql/types/updateMemberDynamicProperties.ts
  src/app/models/company-registration.model.ts
  src/app/models/sector.model.ts
  src/app/modules/registration/components/company-details/company-details.component.ts
  src/app/modules/registration/components/company-details/company-details.layout.ts
  src/app/modules/registration/components/company-details/company-details.model.ts
  src/app/modules/registration/components/company-details/countries.selector.ts
  src/app/modules/registration/components/registration-company-address/registration-company-address.component.ts
  src/app/modules/registration/store/company.effects.ts
  src/app/store/index.ts
  src/app/store/sectors/sectors.actions.spec.ts
  src/app/store/sectors/sectors.actions.ts
  src/app/store/sectors/sectors.effects.spec.ts
  src/app/store/sectors/sectors.effects.ts
  src/app/store/sectors/sectors.reducer.spec.ts
  src/app/store/sectors/sectors.reducer.ts
  src/app/store/sectors/sectors.selectors.spec.ts
  src/app/store/sectors/sectors.selectors.ts
Labels: deploy-demo

#16 VDS-2139: Login as user
  .angulardoc.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/company-name/company-name.component.html
  src/app/components/company-name/company-name.component.scss
  src/app/components/company-name/company-name.component.spec.ts
  src/app/components/company-name/company-name.component.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.spec.ts
  src/app/components/navbar/navbar.component.ts
  src/app/graphql.module.ts
  src/app/graphql/queries/get-current-customer.graphql
  src/app/graphql/types/getCurrentCustomer.ts
  src/app/graphql/types/getDictionaryDynamicPropery.ts
  src/app/modules/errors/errors.component.html
  src/app/modules/errors/errors.component.scss
  src/app/modules/errors/errors.component.spec.ts
  src/app/modules/errors/errors.component.ts
  src/app/modules/errors/errors.module.ts
  src/app/modules/login/components/logged-in/logged-in.component.html
  src/app/modules/login/components/logged-in/logged-in.component.scss
  src/app/modules/login/components/logged-in/logged-in.component.spec.ts
  src/app/modules/login/components/logged-in/logged-in.component.ts
  src/app/modules/login/login-form.layout.ts
  src/app/modules/login/login-form.model.ts
  src/app/modules/login/login-routing.module.ts
  src/app/modules/login/login.component.html
  src/app/modules/login/login.component.scss
  src/app/modules/login/login.component.spec.ts
  src/app/modules/login/login.component.ts
  src/app/modules/login/login.module.ts
  src/app/services/app-initializer.service.ts
  src/app/store/current-customer/current-customer.actions.spec.ts
  src/app/store/current-customer/current-customer.actions.ts
  src/app/store/current-customer/current-customer.effects.spec.ts
  src/app/store/current-customer/current-customer.effects.ts
  src/app/store/current-customer/current-customer.reducer.spec.ts
  src/app/store/current-customer/current-customer.reducer.ts
  src/app/store/current-customer/current-customer.selectors.spec.ts
  src/app/store/current-customer/current-customer.selectors.ts
  src/app/store/index.ts
  src/app/store/login/login.actions.spec.ts
  src/app/store/login/login.actions.ts
  src/app/store/login/login.effects.spec.ts
  src/app/store/login/login.effects.ts
  src/app/store/login/login.reducer.spec.ts
  src/app/store/login/login.reducer.ts
  src/app/store/login/login.selectors.spec.ts
  src/app/store/login/login.selectors.ts
  src/assets/images/login.svg
  src/assets/images/marker.svg
  src/styles/_variables.scss
  src/styles/override/_alerts.scss
Labels: deploy-demo

#29 VDS-1972: Add password policy validation
  src/app/graphql/queries/validate-password.graphql
  src/app/graphql/types/validatePassword.ts
  src/app/modules/registration/components/personal-information/personal-information.model.ts
  src/app/modules/validation/constants/validation-messages.constants.ts
  src/app/modules/validation/validation.module.ts
  src/app/modules/validation/validators/password-policy-validator.service.spec.ts
  src/app/modules/validation/validators/password-policy-validator.service.ts
Labels: deploy-demo, deploy-qa

#32 VDS-2341: Create dashboard component
  .gitignore
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/dashboard-item/dashboard-item.component.html
  src/app/components/dashboard-item/dashboard-item.component.scss
  src/app/components/dashboard-item/dashboard-item.component.spec.ts
  src/app/components/dashboard-item/dashboard-item.component.ts
  src/app/components/dashboard-section/dashboard-section.component.html
  src/app/components/dashboard-section/dashboard-section.component.scss
  src/app/components/dashboard-section/dashboard-section.component.spec.ts
  src/app/components/dashboard-section/dashboard-section.component.ts
  src/app/components/dashboard/dashboard-content.ts
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.scss
  src/app/components/dashboard/dashboard.component.spec.ts
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/navigation-button/navigation-button.component.html
  src/app/components/navigation-button/navigation-button.component.spec.ts
  src/app/modules/checkout/checkout.component.spec.ts
  src/app/modules/checkout/checkout.component.ts
  src/app/services/checkout.service.spec.ts
  src/app/services/checkout.service.ts
  src/app/store/current-customer/current-customer.selectors.ts
  src/assets/images/dash-checkout.svg
  src/assets/images/dash-company.svg
  src/assets/images/dash-login.svg
  src/assets/images/dash-member.svg
  src/styles/_custom.scss
  src/styles/custom/_backgrounds.scss
Labels: deploy-demo, deploy-qa

#33 VDS-2352: Browse list of addresses
  src/app/app-routing.module.ts
  src/app/components/navbar/navbar.component.html
  src/app/graphql/queries/get-organization-addresses.graphql
  src/app/graphql/types/getOrganizationAddresses.ts
  src/app/modules/addresses/addresses-routing.module.ts
  src/app/modules/addresses/addresses.component.html
  src/app/modules/addresses/addresses.component.scss
  src/app/modules/addresses/addresses.component.spec.ts
  src/app/modules/addresses/addresses.component.ts
  src/app/modules/addresses/addresses.constants.ts
  src/app/modules/addresses/addresses.module.ts
  src/app/modules/addresses/store/addresses.actions.spec.ts
  src/app/modules/addresses/store/addresses.actions.ts
  src/app/modules/addresses/store/addresses.effects.spec.ts
  src/app/modules/addresses/store/addresses.effects.ts
  src/app/modules/addresses/store/addresses.reducer.spec.ts
  src/app/modules/addresses/store/addresses.reducer.ts
  src/app/modules/addresses/store/addresses.selectors.spec.ts
  src/app/modules/addresses/store/addresses.selectors.ts
  src/app/store/current-customer/current-customer.reducer.ts
  src/app/store/index.ts
  src/assets/images/arrow-active-down.svg
  src/assets/images/arrow-active-up.svg
  src/assets/images/arrow-down.svg
  src/assets/images/arrow-inactive-down.svg
  src/assets/images/arrow-up.svg
  src/assets/images/context-delete.svg
  src/assets/images/context-pencil.svg
  src/styles/_maps.scss
  src/styles/_variables.scss
  src/styles/custom/_tables.scss
  src/styles/override/_pagination.scss
Labels: deploy-demo

#37 VDS-2369: Usual properties
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/graphql/mutations/update-memberDynamicProperties.graphql
  src/app/graphql/mutations/update-organization.graphql
  src/app/graphql/queries/get-organization.graphql
  src/app/graphql/types/getOrganization.ts
  src/app/graphql/types/updateMemberDynamicProperties.ts
  src/app/graphql/types/updateOrganization.ts
  src/app/helpers/isInteger.ts
  src/app/helpers/nullable.ts
  src/app/models/company.model.ts
  src/app/modules/companies/companies.module.ts
  src/app/modules/companies/components/company-edit/company-edit-form.layout.ts
  src/app/modules/companies/components/company-edit/company-edit.component.html
  src/app/modules/companies/components/company-edit/company-edit.component.ts
  src/app/modules/companies/components/company-properties/company-properties.component.html
  src/app/modules/companies/components/company-properties/company-properties.component.scss
  src/app/modules/companies/components/company-properties/company-properties.component.spec.ts
  src/app/modules/companies/components/company-properties/company-properties.component.ts
  src/app/modules/companies/components/company-properties/company-properties.model.ts
  src/app/modules/companies/components/usual-properties/usual-properties.component.html
  src/app/modules/companies/components/usual-properties/usual-properties.component.scss
  src/app/modules/companies/components/usual-properties/usual-properties.component.spec.ts
  src/app/modules/companies/components/usual-properties/usual-properties.component.ts
  src/app/modules/companies/components/usual-properties/usual-properties.model.ts
  src/app/modules/companies/constants/dynamic-properties.ts
  src/app/modules/companies/store/companies.actions.ts
  src/app/modules/companies/store/companies.effects.ts
  src/app/modules/companies/store/companies.reducer.ts
  src/app/modules/companies/store/companies.selectors.ts
  src/app/modules/dynamic-forms/adapters/ngb-time-native-utc-adapter.spec.ts
  src/app/modules/dynamic-forms/adapters/ngb-time-native-utc-adapter.ts
  src/app/modules/dynamic-forms/components/dynamic-ng-bootstrap-datetime-picker/dynamic-datetime-picker.model.ts
  src/app/modules/dynamic-forms/components/dynamic-ng-bootstrap-datetime-picker/dynamic-ng-bootstrap-datetime-picker.component.html
  src/app/modules/dynamic-forms/components/dynamic-ng-bootstrap-datetime-picker/dynamic-ng-bootstrap-datetime-picker.component.scss
  src/app/modules/dynamic-forms/components/dynamic-ng-bootstrap-datetime-picker/dynamic-ng-bootstrap-datetime-picker.component.spec.ts
  src/app/modules/dynamic-forms/components/dynamic-ng-bootstrap-datetime-picker/dynamic-ng-bootstrap-datetime-picker.component.ts
  src/app/modules/dynamic-forms/dynamic-forms.module.ts
  src/app/modules/validation/constants/validation-messages.constants.ts
  src/styles/_custom.scss
  src/styles/_override.scss
  src/styles/_variables.scss
  src/styles/custom/_forms.scss
  src/styles/custom/_popover.scss
  src/styles/override/_custom-forms.scss
  src/styles/override/_form-checks.scss
  webpack.config.js
Labels: deploy-qa

#40 VDS-2234: Create new address
  src/app/modules/addresses/addresses.component.html
  src/app/modules/addresses/addresses.component.ts
  src/app/modules/addresses/components/address-edit/address-edit.component.html
  src/app/modules/addresses/components/address-edit/address-edit.component.spec.ts
  src/app/modules/addresses/components/address-edit/address-edit.component.ts
  src/app/modules/addresses/store/addresses.actions.ts
  src/app/modules/addresses/store/addresses.effects.spec.ts
  src/app/modules/addresses/store/addresses.effects.ts
  src/app/modules/addresses/store/addresses.reducer.ts
Labels: deploy-demo, deploy-qa

#44 Refetch query for organization addresses
  src/app/modules/addresses/store/addresses.effects.ts
Labels: deploy-demo, deploy-qa

#31 VDS-2522 Use the form group validator for the password matching validator
  src/app/modules/registration/components/personal-information/personal-information.model.ts
  src/app/modules/validation/validators/password-match-validator.ts
Labels: deploy-demo
