Repository VirtoCommerce/vc-demo-xapi-app, pull requests merged in 2021-09, with the labels that each got.

#45 VDS-2384: Create shortText + Dictionary component
  .gitignore
  src/app/graphql/queries/get-dictionaryDynamicProperty.graphql
  src/app/graphql/queries/get-organization.graphql
  src/app/graphql/types/getDictionaryDynamicProperty.ts
  src/app/graphql/types/getOrganization.ts
  src/app/models/company.model.ts
  src/app/modules/companies/companies.module.ts
  src/app/modules/companies/components/company-edit/company-edit.component.html
  src/app/modules/companies/components/company-edit/company-edit.component.ts
  src/app/modules/companies/components/dictionary/dictionary.component.html
  src/app/modules/companies/components/dictionary/dictionary.component.scss
  src/app/modules/companies/components/dictionary/dictionary.component.spec.ts
  src/app/modules/companies/components/dictionary/dictionary.component.ts
  src/app/modules/companies/components/dictionary/dictionary.model.ts
  src/app/modules/companies/store/companies.effects.ts
  src/app/modules/companies/store/companies.reducer.ts
  src/app/modules/companies/store/companies.selectors.spec.ts
  src/app/modules/companies/store/companies.selectors.ts
  src/app/store/index.ts
  src/app/store/sectors/sectors.actions.ts
  src/app/store/sectors/sectors.effects.ts
  src/app/store/sectors/sectors.reducer.ts
Labels: deploy-demo, deploy-qa

#48 VDS-2783: Fix regex
  src/app/modules/companies/store/companies.reducer.ts
Labels: deploy-demo, deploy-qa

#59 VDS-2812: Workaround for work with dictionary property
  src/app/modules/companies/store/companies.reducer.ts
  src/app/modules/companies/store/companies.selectors.ts
Labels: deploy-demo, deploy-qa

#60 VDS-2374: Add multilingual properties
  src/app/graphql/queries/get-organization.graphql
  src/app/graphql/types/getOrganization.ts
  src/app/models/company.model.ts
  src/app/modules/companies/companies.module.ts
  src/app/modules/companies/components/company-edit/company-edit.component.html
  src/app/modules/companies/components/company-edit/company-edit.component.ts
  src/app/modules/companies/components/multilanguage-properties/multilingual-properties.component.html
  src/app/modules/companies/components/multilanguage-properties/multilingual-properties.component.scss
  src/app/modules/companies/components/multilanguage-properties/multilingual-properties.component.spec.ts
  src/app/modules/companies/components/multilanguage-properties/multilingual-properties.component.ts
  src/app/modules/companies/components/multilanguage-properties/multilingual-properties.model.ts
  src/app/modules/companies/store/companies.actions.ts
  src/app/modules/companies/store/companies.effects.ts
  src/app/modules/companies/store/companies.reducer.ts
  src/app/modules/companies/store/companies.selectors.spec.ts
  src/app/modules/companies/store/companies.selectors.ts
Labels: deploy-qa

#61 VDS-2329: Add new member
  src/app/app-routing.module.ts
  src/app/models/member.model.ts
  src/app/modules/companies/store/companies.reducer.ts
  src/app/modules/members/components/add-member/add-member.component.html
  src/app/modules/members/components/add-member/add-member.component.scss
  src/app/modules/members/components/add-member/add-member.component.spec.ts
  src/app/modules/members/components/add-member/add-member.component.ts
  src/app/modules/members/members-routing.module.ts
  src/app/modules/members/members.module.ts
  src/app/modules/members/store/members.actions.spec.ts
  src/app/modules/members/store/members.actions.ts
  src/app/modules/members/store/members.effects.spec.ts
  src/app/modules/members/store/members.effects.ts
  src/app/modules/members/store/members.reducer.spec.ts
  src/app/modules/members/store/members.reducer.ts
  src/app/modules/members/store/members.selectors.spec.ts
  src/app/modules/members/store/members.selectors.ts
  src/app/store/current-customer/current-customer.reducer.ts
  src/app/store/index.ts
Labels: deploy-qa

#62 VDS--2518: Add new member form fields validation
  .eslintrc.json
  src/app/modules/members/components/add-member/add-member.component.html
  src/app/modules/members/components/add-member/add-member.component.ts
  src/app/modules/members/store/members.actions.ts
  src/app/modules/members/store/members.effects.ts
  src/app/modules/members/store/members.reducer.ts
Labels: deploy-demo, deploy-qa

#63 VDS-2444: Added user must change password
  src/app/graphql/types/globalTypes.ts
  src/app/modules/members/store/members.effects.ts
Labels: deploy-demo, deploy-qa

#64 VDS-2428 [Add new member to company] Email and User name should be unique
  src/app/modules/members/components/add-member/add-member.component.html
  src/app/modules/members/components/add-member/add-member.component.ts
Labels: deploy-demo

#65 VDS-2435: Validate passwords by password policy
  src/app/modules/members/components/add-member/add-member.component.html
  src/app/modules/members/components/add-member/add-member.component.ts
  src/app/modules/validation/validators/password-policy-validator.service.ts
Labels: deploy-qa

#66 VDS-2435: Remove workarounds
  src/app/modules/members/components/add-member/add-member.component.html
  src/app/modules/members/components/add-member/add-member.component.ts
Labels: deploy-demo, deploy-qa

#67 VDS-2780: Implement frontend part of Reset password scenario
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/thank-you/thank-you.component.html
  src/app/components/thank-you/thank-you.component.scss
  src/app/components/thank-you/thank-you.component.spec.ts
  src/app/components/thank-you/thank-you.component.ts
  src/app/graphql/mutations/reset-password-by-token.graphql
  src/app/graphql/queries/request-password-reset.graphql
  src/app/graphql/types/globalTypes.ts
  src/app/graphql/types/requestPasswordReset.ts
  src/app/graphql/types/resetPasswordByToken.ts
  src/app/modules/login/login.component.html
  src/app/modules/members/store/members.effects.ts
  src/app/modules/registration/components/thank-you/thank-you.component.html
  src/app/modules/registration/components/thank-you/thank-you.component.ts
  src/app/modules/registration/registration-routing.module.ts
  src/app/modules/registration/registration.module.ts
  src/app/modules/registration/store/company.effects.ts
  src/app/modules/reset-password/email-request/email-request.component.html
  src/app/modules/reset-password/email-request/email-request.component.scss
  src/app/modules/reset-password/email-request/email-request.component.spec.ts
  src/app/modules/reset-password/email-request/email-request.component.ts
  src/app/modules/reset-password/reset-password-form/reset-password-form.component.html
  src/app/modules/reset-password/reset-password-form/reset-password-form.component.scss
  src/app/modules/reset-password/reset-password-form/reset-password-form.component.spec.ts
  src/app/modules/reset-password/reset-password-form/reset-password-form.component.ts
  src/app/modules/reset-password/reset-password-routing.module.ts
  src/app/modules/reset-password/reset-password.module.ts
  src/app/modules/validation/constants/validation-messages.constants.ts
Labels: deploy-demo, deploy-qa

#68 VDS-2855 Solve problem with the not empty HTML input at languege changing
  src/app/modules/companies/store/companies.actions.ts
  src/app/modules/companies/store/companies.effects.ts
  src/app/modules/companies/store/companies.reducer.ts
Labels: deploy-demo

#71 VDS-2877: Implement companies listing
  src/app/graphql/queries/get-current-customer.graphql
  src/app/graphql/queries/get-organizations.graphql
  src/app/graphql/types/getCurrentCustomer.ts
  src/app/graphql/types/getOrganizations.ts
  src/app/graphql/types/globalTypes.ts
  src/app/models/companies-listing-item.model.ts
  src/app/modules/companies/companies.component.html
  src/app/modules/companies/companies.component.spec.ts
  src/app/modules/companies/companies.component.ts
  src/app/modules/companies/companies.module.ts
  src/app/modules/companies/components/companies-list-filter-bar/companies-list-filter-bar.component.html
  src/app/modules/companies/components/companies-list-filter-bar/companies-list-filter-bar.component.scss
  src/app/modules/companies/components/companies-list-filter-bar/companies-list-filter-bar.component.spec.ts
  src/app/modules/companies/components/companies-list-filter-bar/companies-list-filter-bar.component.ts
  src/app/modules/companies/components/companies-list-filter-bar/filter-values.model.ts
  src/app/modules/companies/components/option-filter/option-filter.component.html
  src/app/modules/companies/components/option-filter/option-filter.component.scss
  src/app/modules/companies/components/option-filter/option-filter.component.spec.ts
  src/app/modules/companies/components/option-filter/option-filter.component.ts
  src/app/modules/companies/components/search-filter/search-filter.component.html
  src/app/modules/companies/components/search-filter/search-filter.component.scss
  src/app/modules/companies/components/search-filter/search-filter.component.spec.ts
  src/app/modules/companies/components/search-filter/search-filter.component.ts
  src/app/modules/companies/constants/pageInfo.ts
  src/app/modules/companies/store/companies.actions.ts
  src/app/modules/companies/store/companies.effects.ts
  src/app/modules/companies/store/companies.reducer.ts
  src/app/modules/companies/store/companies.selectors.ts
  src/app/store/current-customer/current-customer.reducer.ts
Labels: deploy-qa

#72 VDS-2185, VDS-2239, VDS-2289: Members list with full-text search and filter by status
  src/app/components/dashboard/dashboard-content.ts
  src/app/graphql/queries/get-organization-members.graphql
  src/app/graphql/types/getOrganizationMembers.ts
  src/app/graphql/types/globalTypes.ts
  src/app/models/member.model.ts
  src/app/modules/members/components/members-list/members-list-filter-bar/filter-values.model.ts
  src/app/modules/members/components/members-list/members-list-filter-bar/members-list-filter-bar.component.html
  src/app/modules/members/components/members-list/members-list-filter-bar/members-list-filter-bar.component.scss
  src/app/modules/members/components/members-list/members-list-filter-bar/members-list-filter-bar.component.spec.ts
  src/app/modules/members/components/members-list/members-list-filter-bar/members-list-filter-bar.component.ts
  src/app/modules/members/components/members-list/members-list-filter-bar/option-filter/option-filter.component.html
  src/app/modules/members/components/members-list/members-list-filter-bar/option-filter/option-filter.component.scss
  src/app/modules/members/components/members-list/members-list-filter-bar/option-filter/option-filter.component.spec.ts
  src/app/modules/members/components/members-list/members-list-filter-bar/option-filter/option-filter.component.ts
  src/app/modules/members/components/members-list/members-list-filter-bar/search-filter/search-filter.component.html
  src/app/modules/members/components/members-list/members-list-filter-bar/search-filter/search-filter.component.scss
  src/app/modules/members/components/members-list/members-list-filter-bar/search-filter/search-filter.component.spec.ts
  src/app/modules/members/components/members-list/members-list-filter-bar/search-filter/search-filter.component.ts
  src/app/modules/members/components/members-list/members-list-pagination/members-list-pagination.component.html
  src/app/modules/members/components/members-list/members-list-pagination/members-list-pagination.component.scss
  src/app/modules/members/components/members-list/members-list-pagination/members-list-pagination.component.spec.ts
  src/app/modules/members/components/members-list/members-list-pagination/members-list-pagination.component.ts
  src/app/modules/members/components/members-list/members-list-table/action-buttons/action-buttons.component.html
  src/app/modules/members/components/members-list/members-list-table/action-buttons/action-buttons.component.scss
  src/app/modules/members/components/members-list/members-list-table/action-buttons/action-buttons.component.spec.ts
  src/app/modules/members/components/members-list/members-list-table/action-buttons/action-buttons.component.ts
  src/app/modules/members/components/members-list/members-list-table/member-state/member-state.component.html
  src/app/modules/members/components/members-list/members-list-table/member-state/member-state.component.scss
  src/app/modules/members/components/members-list/members-list-table/member-state/member-state.component.spec.ts
  src/app/modules/members/components/members-list/members-list-table/member-state/member-state.component.ts
  src/app/modules/members/components/members-list/members-list-table/member-status/member-status.component.html
  src/app/modules/members/components/members-list/members-list-table/member-status/member-status.component.scss
  src/app/modules/members/components/members-list/members-list-table/member-status/member-status.component.spec.ts
  src/app/modules/members/components/members-list/members-list-table/member-status/member-status.component.ts
  src/app/modules/members/components/members-list/members-list-table/members-list-table.component.html
  src/app/modules/members/components/members-list/members-list-table/members-list-table.component.scss
  src/app/modules/members/components/members-list/members-list-table/members-list-table.component.spec.ts
  src/app/modules/members/components/members-list/members-list-table/members-list-table.component.ts
  src/app/modules/members/components/members-list/members-list.component.html
  src/app/modules/members/components/members-list/members-list.component.scss
  src/app/modules/members/components/members-list/members-list.component.spec.ts
  src/app/modules/members/components/members-list/members-list.component.ts
  src/app/modules/members/components/members-list/members-list.constants.ts
  src/app/modules/members/members-routing.module.ts
  src/app/modules/members/members.module.ts
  src/app/modules/members/store/members.actions.ts
  src/app/modules/members/store/members.effects.ts
  src/app/modules/members/store/members.reducer.ts
  src/app/modules/members/store/members.selectors.ts
  src/assets/images/status-Active.svg
  src/assets/images/status-Inactive.svg
Labels: deploy-demo, deploy-qa

#74 VDS-2311 Delete company member
  src/app/graphql.module.ts
  src/app/graphql/mutations/delete-contact.graphql
  src/app/graphql/mutations/delete-users.graphql
  src/app/graphql/queries/get-organization-members.graphql
  src/app/graphql/types/deleteContact.ts
  src/app/graphql/types/deleteUsers.ts
  src/app/graphql/types/getOrganizationMembers.ts
  src/app/graphql/types/globalTypes.ts
  src/app/modules/members/components/members-list/members-list-table/action-buttons/action-buttons.component.ts
  src/app/modules/members/components/members-list/members-list-table/members-list-table.component.html
  src/app/modules/members/components/members-list/members-list-table/members-list-table.component.ts
  src/app/modules/members/components/members-list/members-list.component.html
  src/app/modules/members/components/members-list/members-list.component.ts
  src/app/modules/members/components/members-list/members-list.constants.ts
  src/app/modules/members/store/members.actions.ts
  src/app/modules/members/store/members.effects.ts
  src/app/modules/members/store/members.reducer.ts
Labels: deploy-demo

#75 VDS-3041 Dissable the delete btn if a member is a current customer
  src/app/modules/members/components/members-list/members-list-table/action-buttons/action-buttons.component.html
  src/app/modules/members/components/members-list/members-list-table/action-buttons/action-buttons.component.ts
  src/app/modules/members/components/members-list/members-list-table/members-list-table.component.html
  src/app/modules/members/components/members-list/members-list-table/members-list-table.component.ts
  src/app/modules/members/components/members-list/members-list.component.html
  src/app/modules/members/components/members-list/members-list.component.ts
  src/app/store/current-customer/current-customer.reducer.ts
Labels: deploy-demo
